[package]
name = "convit"
version = "0.1.0"
edition = "2021"

[dependencies]
comfy-table = "7.1.1"
crossterm = "0.27.0"
ratatui = "0.26.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
term-table = "1.3.2"
thiserror = "1.0.61"
